//
import "@/src/globals.css"

//
import { cookies } from "next/headers"
import { NextIntlClientProvider } from "next-intl"

//
import { BaseLayout } from "@/src/ui/layouts/BaseLayout"

//
import type { Metadata } from "next"

//
export const metadata: Metadata = {
  title: "Dev Connect",
  description: "Generated by create next app",
}

//
export default async function RootLayout({ children, }: Readonly<{ children: React.ReactNode }>) {

  const [cookieStore] = await Promise.all([
    cookies(),
  ])

  return (
    <NextIntlClientProvider>
      <BaseLayout locale={cookieStore.get("NEXT_LOCALE")?.value || "pt"}>
        {children}
      </BaseLayout>
    </NextIntlClientProvider>
  )
}
